INSERT INTO scp (item_number,name,class,series,img) values('SCP-001','TOP SECRET','REDACTED','REDACTED','https://i.pinimg.com/originals/78/06/a4/7806a4310b0bab53e87f209047ffff5c.jpg');
INSERT INTO scp (item_number,name,class,series,img) values('SCP-002','The "Living" Room','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-003','Biological Motherboard','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-004','The 12 Rusty Keys and the Door','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-005','Skeleton Key','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-006','Fountain of Youth','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-007','Abdominal Planet','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-008','Zombie Plague','CLASS 4 VERIFICATION REQUIRED','REDACTED');
INSERT INTO scp (item_number,name,class,series,img) values('SCP-009','Red Ice','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-010','Collars of Control','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-011','Sentient Civil War Memorial Statue','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-012','A Bad Composition','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-013','Blue Lady Cigarettes','Safe','1');
INSERT INTO scp (item_number,name,class,series,img) values('SCP-014','The Concrete Man','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-015','Pipe Nightmare','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-016','Sentient Micro-Organism','Keter',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-017','Shadow Person','Keter',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-018','Super Ball','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-019','The Monster Pot','Keter',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-020','Unseen Mold','Keter',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-021','Skin Wyrm','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-022','The Morgue','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-023','Black Shuck','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-024','Game Show of Death','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-025','A Well-Worn Wardrobe','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-026','Afterschool Retention','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-027','The Vermin God','Euclid',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-028','Knowledge','Safe',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-029','Daughter of Shadows','Keter',1);
INSERT INTO scp (item_number,name,class,series,img) values('SCP-030','The Homunculus','Safe',1);